# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informationapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
