# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-15 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumen',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
    ]
